### ISSUE TITLE
 error: package me.madhead.aws_junit5.common does not exist import me.madhead.aws_junit5.common.AWSClient;                                    ^

### ISSUE THREAD

**Issue by jjayaraman** [madhead/aws-junit5#9]
Thanks for all the great libraries.

In my Gradle config I have this.

    testImplementation 'me.madhead.aws-junit5:s3-v1:6.0.3'

And getting the below error when running the Test case. But this file exists when I do control click from the IDEA IDE, it opens this file from the jar.  Not sure why I still get this error at runtime.

 error: package me.madhead.aws_junit5.common does not exist
import me.madhead.aws_junit5.common.AWSClient;
                                   ^

**Comment by madhead** [comment]
Ok, I had wrong scopes (for the "V1" versions only) in the resulting POMs. I fixed them, but this is kind of breaking change (not really, but the dependency tree has changed), so I've released a new version: `7.0.0`.

It will be there in the Maven Central in a few hours. Please, use it.

Thank you for reporting!

**Comment by madhead** [comment]
There was another issue with the generated POMs (#11), so there is a newer version: `7.0.1`
